### ISSUE TITLE
QQ音乐验证码无法完全显示

### ISSUE THREAD

**Issue by Sciroccogti** [gorquan/deepin-wine-docker#5]
1. 平台：Ubuntu16.04
2. 软件：qqmusic

![图片](https://user-images.githubusercontent.com/32357397/73734928-689dac00-4779-11ea-96a9-f1bbcf1f5832.png)

（一般来说关闭VPN可以解决这一问题）

**Comment by gorquan** [comment]
点击取消再登录就不会有验证码了，是有这个bug，等过段时间有空了我会处理一下

**Comment by gorquan** [comment]
新版本应该不会有这种问题出现了，你可以用新版本测试一下
